// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "HomePage": {
        "title": "Project setup",
        "description": "Initial project setup",
        "heading": "Home Page"
    }
};
export default messages;